#!/usr/bin/env node

const DEBUG=false;

//Will return the different of the previous year from the current year population growth
function calculateYearGrowth (previous, current) {
  return current - previous;
}


// Asynchronous Call
(async () => {
    try {
      const res = await fetch('https://datausa.io/api/data?drilldowns=Nation&measures=Population');

      const headerDate = res.headers && res.headers.get('date') ? res.headers.get('date') : 'no response date';
      console.log('Status Code:', res.status);
      console.log('Date in Response header:', headerDate);
  
      const yearData = await res.json();
 
      (DEBUG == true) && console.debug(yearData);

      let prevYearPop = -1;
      let yearInfo = {};

      for(yearInfo of yearData.data.reverse()) {
        let curYearPop = yearInfo.Population;
        console.log ('-------------------------------------------------------');
        console.log(`yearInfo Year: ${yearInfo.Year}, Population: ${yearInfo.Population}`);
        console.log(`Nation ID: ` + yearInfo['ID Nation'] + `: yearInfo Year ${yearInfo.Year}, Population: ${yearInfo.Population}`);

        if (prevYearPop == -1) {
          prevYearPop = yearInfo.Population;
        }
        else {
          console.log (`Growth from previous year ` + calculateYearGrowth(prevYearPop,curYearPop));
          prevYearPop = curYearPop;
        }
      }
      console.log ('-------------------------------------------------------');
      console.log();
    } catch (err) {
      console.log(err.message); //can be console.error
    }
  })();