#!/usr/bin/env node

//run this script: ./helloworld

//This Script will echo hello world and do some very basic node scripting

console.log ("Hello World");

const array = [1,2,3,4,5,6,7,8,9,10];

array.reverse().forEach ((element) => {
    console.log (element);
});

console.log ("Lift Off");